# Generated by Django 6.1 on 2026-09-12 12:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Filmin adı')),
                ('genre', models.CharField(choices=[('Action', 'Döyüş (Action)'), ('Comedy', 'Komediya (Comedy)'), ('Drama', 'Dram (Drama)'), ('Sci-Fi', 'Elmi fantastika (Sci-Fi)'), ('Horror', 'Dəhşət (Horror)'), ('Romance', 'Romantik (Romance)'), ('Thriller', 'Triller (Thriller)'), ('Animation', 'Animasiya (Animation)'), ('Documentary', 'Sənədli (Documentary)'), ('Adventure', 'Macəra (Adventure)'), ('Fantasy', 'Fantastika (Fantasy)'), ('Other', 'Digər')], max_length=50, verbose_name='Janr')),
                ('release_year', models.PositiveIntegerField(verbose_name='Buraxılış ili')),
                ('status', models.CharField(choices=[('want_to_watch', 'Baxmaq istəyirəm'), ('watching', 'Baxıram'), ('watched', 'Baxmışam')], default='want_to_watch', max_length=20, verbose_name='Status')),
                ('rating', models.PositiveSmallIntegerField(help_text='1 ilə 10 arasında bir qiymət daxil edin', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Şəxsi qiymətləndirmə (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə olunma tarixi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL, verbose_name='Filmin sahibi')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmlər',
                'ordering': ['-created_at'],
            },
        ),
    ]
